const config = {
  business: {
    name: "Stellar Roofing & Restorations",
    legalName: "Stellar Roofing & Restorations LLC",
    tagline: "Out of This World Roofing",
    ownerName: "Nate",
    description: "Nashville's trusted roofing company providing residential and commercial roofing services with lifetime warranties and free inspections.",
    yearFounded: 2020,
    phone: "(629) 277-4249",
    phoneRaw: "6292774249",
    email: "Office@thestellarroofing.com",
    website: "https://thestellarroofing.com",
    address: {
      type: "service-area",
      city: "Nashville",
      state: "TN",
      stateFullName: "Tennessee",
      country: "US",
    },
    hours: {
      weekdays: "7:00 AM - 7:00 PM",
      saturday: "8:00 AM - 5:00 PM",
      sunday: "Closed",
      schemaFormat: ["Mo-Fr 07:00-19:00", "Sa 08:00-17:00"],
    },
  },
  brand: {
    colors: {
      primary: "#0B1547",
      primaryLight: "#1a2a6b",
      accent: "#FFFFFF",
      accentHover: "#F1F5F9",
    },
    logo: {
      primary: "/images/logo.png",
      mascotThumbsup: "/images/logo-mascot-thumbsup.png",
      mascotPhone: "/images/logo-mascot-phone.png",
      width: 180,
      height: 60,
    },
  },
  photos: {
    hero: "hero.jpg",
    serviceRoofReplacement: "service-roof-replacement.jpg",
    serviceRoofRepair: "service-roof-repair.jpg",
    serviceStormDamage: "service-storm-damage.jpg",
    serviceStormDamageHome: "service-storm-damage-home.jpg",
    serviceInspection: "service-inspection.jpg",
    serviceCommercial: "service-commercial.jpg",
    serviceEmergency: "service-storm-damage.jpg",
    crewWorking: "crew-working.jpg",
    crewWorking02: "crew-working-02.jpg",
    project01: "project-01.jpg",
    project02: "project-02.jpg",
  },
  services: [
    { name: "Roof Replacement", slug: "roof-replacement", shortDescription: "Complete roof replacement with premium materials and lifetime warranty.", icon: "Home", photo: "service-roof-replacement.jpg" },
    { name: "Roof Repair", slug: "roof-repair", shortDescription: "Fast, reliable roof repairs for leaks, missing shingles, and storm damage.", icon: "Wrench", photo: "service-roof-repair.jpg" },
    { name: "Storm Damage Repair", slug: "storm-damage-repair", shortDescription: "Expert storm damage assessment and repair with insurance claims assistance.", icon: "CloudLightning", photo: "service-storm-damage.jpg" },
    { name: "Roof Inspection", slug: "roof-inspection", shortDescription: "Free, no-obligation roof inspections with honest assessments.", icon: "Search", photo: "service-inspection.jpg" },
    { name: "Commercial Roofing", slug: "commercial-roofing", shortDescription: "Commercial roofing solutions for businesses of all sizes.", icon: "Building2", photo: "service-commercial.jpg" },
    { name: "Emergency Roof Repair", slug: "emergency-roof-repair", shortDescription: "Fast emergency response for urgent roof problems and active leaks.", icon: "AlertTriangle", photo: "service-storm-damage.jpg" },
  ],
  serviceAreas: {
    primary: { city: "Nashville", state: "TN", slug: "nashville" },
    mvp: [
      { city: "Nashville", state: "TN", slug: "nashville" },
      { city: "Murfreesboro", state: "TN", slug: "murfreesboro" },
      { city: "Clarksville", state: "TN", slug: "clarksville" },
      { city: "Franklin", state: "TN", slug: "franklin" },
      { city: "Brentwood", state: "TN", slug: "brentwood" },
    ],
    expansion: [
      { city: "Hendersonville", state: "TN", slug: "hendersonville" },
      { city: "Gallatin", state: "TN", slug: "gallatin" },
      { city: "Smyrna", state: "TN", slug: "smyrna" },
      { city: "Spring Hill", state: "TN", slug: "spring-hill" },
      { city: "Mount Juliet", state: "TN", slug: "mount-juliet" },
      { city: "Lebanon", state: "TN", slug: "lebanon" },
    ],
  },
  trustSignals: [
    { label: "Lifetime Warranty", icon: "Shield" },
    { label: "Free Inspections", icon: "SearchCheck" },
    { label: "Licensed & Insured", icon: "BadgeCheck" },
    { label: "Insurance Claims Help", icon: "FileCheck" },
  ],
  ghl: {
    quoteFormId: "REPLACE_WITH_GHL_FORM_ID",
    contactFormId: "REPLACE_WITH_GHL_CONTACT_FORM_ID",
    reviewWidgetId: "REPLACE_WITH_GHL_REVIEW_WIDGET_ID",
  },
  seo: {
    titleSuffix: " | Stellar Roofing & Restorations",
    defaultOgImage: "/images/hero.jpg",
  },
};

export default config;
